version: '3.8'

services:
  web:
    image: python:3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - sqlite_data:/app/db.sqlite3 # SQLite faylini saqlash uchun volume
    ports:
      - "8989:8989"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
volumes:
  sqlite_data:
